### ISSUE TITLE
n and p for movement

### ISSUE THREAD

**Issue by aecay** [flexibeast/ewmctrl#5]
This is a very nice library, I can see it being very useful.  However, I would expect the n and p keys to move to the next and previous lines, just like in other special modes (dired, proced, ...).  So, this is a feature request to make this change.

The "rename window" function on n could be rebound to r.  The put-window function on p could be rebound to P, or to m (for "move" window).

**Comment by flexibeast** [comment]
Thank you for your kind words!

Sorry for not having followed Emacs conventions in this regard; i prefer to use 'j' and 'k' instead of 'n' and 'p', and so forgot about these conventions when assigning keybindings.

i've now bound 'n' to `next-line`, and 'p' to `previous-line`.

i'd used 'p' ("put") instead of 'm' ("move") for shifting a window between desktops because i wanted to keep 'm' available for "move"ing a window around a given desktop; but i now feel it's more likely that people will more often want to use `ewmctrl` to move windows between desktops than within them. So 'm' now does the former, and i'm going to keep 'M' reserved for the latter.

i want to keep 'r' reserved for "resize", so have now bound 'N' to `ewmctrl-change-window-name` and 'I' to `ewmctrl-change-window-icon-name`, for consistency. i seem to recall that in some contexts, the "icon name" will be the thing users expect to be affected by a rename, and so have chosen these particular bindings to avoid a priority conflict over the binding for 'R'.

**Comment by aecay** [comment]
Great, thanks for the quick response!  I'm going to go ahead and close this issue because it seems resolved to me -- feel free to open it again though if you think it needs to stay open.

**Comment by flexibeast** [comment]
You're welcome - thanks!
